FROM alpine:3.22

RUN apk --no-cache add ca-certificates && \
    adduser -D -H -s /sbin/nologin gonsul

ARG TARGETPLATFORM
COPY ${TARGETPLATFORM}/gonsul /usr/bin/gonsul

USER gonsul
ENTRYPOINT ["/usr/bin/gonsul"]
