name: 'Checks and tests'

on:
  push:
    branches:
      - 'master'
      - 'refactoring_and_improvement'
  pull_request:
    branches:
      - 'master'

permissions:
  contents: read

jobs:
  markdown:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repo
        uses: 'actions/checkout@v6'
      - name: Install Node.js
        uses: 'actions/setup-node@v6'
        with:
          node-version: 24
      - name: Install markdownlint
        run: npm install -g markdownlint-cli
      - name: Lint Markdown files
        run: make markdownlint

  tests:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repo
        uses: 'actions/checkout@v6'
      - name: Install Go
        uses: 'actions/setup-go@v6'
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Format
        run: make fmt-check
      - name: Tests
        run: go test ./...
      - name: Race tests
        run: go test -race ./...
      - name: Vet
        run: go vet ./...
      - name: Build
        run: make build
      - name: What's left behind (if anything)
        run: git status
      - name: Make sure nothing is left uncommitted
        run: git diff --exit-code 1> /dev/null

  security:
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repo
        uses: 'actions/checkout@v6'
      - name: Install Go
        uses: 'actions/setup-go@v6'
        with:
          go-version-file: 'go.mod'
          cache: true
      - name: Vulnerability scan
        run: make vulncheck
